apiVersion: v1
kind: Service

metadata:
  name: mozubayer-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:342680862663:certificate/a2f8be82-1e0d-4754-9b60-c9afe1c676ae
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"

spec:
  selector:
    app.kubernetes.io/name: timeoffapp

  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 80

  type: LoadBalancer
